services: 
  url: 
    build: .
    depends_on:
      - mongo
    env_file:
      - .env
    ports: 
      - "3000:3000"

  mongo: 
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes: 
  mongo_data: